import { ovo, skranji } from "@/utils/fonts";
import "./globals.css";

export const metadata = {
  title: "Ctrl - Studio",
  description: "Generated by create next app",
  icons: {
    icon: "/public/favicon.svg",
    shortcut: "/public/favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body
        className={`${skranji.variable} ${ovo.variable} font-skranji antialiased leading-8 overflow-x-hidden bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
