/**
 * The root layout for the application.
 * Note: The primary HTML structure is in the [lang]/layout.js file.
 * This layout simply passes its children through.
 */
import "./globals.css";

export const metadata = {
  title: "Ctrl - Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return children;
}
