import { locales } from "../dictionaries";
import { ovo, skranji } from "@/utils/fonts";
import "../globals.css";

export async function generateStaticParams() {
  return locales.map((lang) => ({ lang }));
}

export const metadata = {
  title: "Ctrl - Studio",
  description: "Generated by create next app",
};

export default async function LangLayout({ children, params }) {
  const { lang } = await params;

  return (
    <html lang={lang} suppressHydrationWarning className="scroll-smooth">
      <body
        className={`${skranji.variable} ${ovo.variable} font-skranji antialiased leading-8 overflow-x-hidden bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
